// 【exStatus の指定パターン】
// ex_purchased : 「EXあり（購入済）」のみ
// ex_p_exa_u   : 「EXあり（購入済）」＋「EXAあり（未購入）」
// ex_u_exa_p   : 「EXあり（未購入）」＋「EXAあり（購入済）」
// ex_p_exa_p   : 「EXあり（購入済）」＋「EXAあり（購入済）」
// ex_u_exa_u   : 「EXあり（未購入）」＋「EXAあり（未購入）」
// none         : 「EXなし」
// 【type の指定パターン】
// ★「コンセプトボイス」「セリフボイス」「ルート選択ボイス」のいずれか

const voiceData = [
  {
    id: 1,
    title: "束縛ボイス",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♡♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-00062_A.html"
  },
  {
    id: 2,
    title: "束縛ボイスvol.2",
    liver: "赤城ウェン",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "https://shop.nijisanji.jp/dig-00096_A.html",
    url: ""
  },
  {
    id: 3,
    title: "ヒーローボイス",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-01489.html"
  },
  {
    id: 4,
    title: "ほろ酔いボイスvol.2",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-01456.html"
  },
  {
    id: 5,
    title: "家族パロディボイスvol.2",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 6,
    title: "がんばらないボイス",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 7,
    title: "わがままボイス",
    liver: "赤城ウェン",
    type: "セリフボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 8,
    title: "ツンデレボイス",
    liver: "赤城ウェン",
    type: "セリフボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 9,
    title: "ジューンブライドボイス2024",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 10,
    title: "ホワイトデーボイス2024",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 11,
    title: "シェアハウスボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 12,
    title: "お迎えボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 13,
    title: "キミと夜空ボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 14,
    title: "夜更かしボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 15,
    title: "パーティーボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 16,
    title: "アイドルパロディボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 17,
    title: "ほろ酔いボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 18,
    title: "ほろ酔いボイスvol.2",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 19,
    title: "ミニライバーボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 20,
    title: "Shoothing Voice",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 21,
    title: "束縛ボイスvol.2",
    liver: "伊波ライ",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 22,
    title: "バレンタインボイス2024",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 23,
    title: "わがままボイス",
    liver: "伊波ライ",
    type: "セリフボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 24,
    title: "ツンデレボイス",
    liver: "伊波ライ",
    type: "セリフボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 25,
    title: "バレンタインボイス2024",
    liver: "宇佐美リト",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 26,
    title: "束縛ボイスvol.2",
    liver: "宇佐美リト",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 27,
    title: "バレンタインボイス2019",
    liver: "卯月コウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 28,
    title: "ホワイトデーボイス2019",
    liver: "卯月コウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 29,
    title: "ヴィランボイス",
    liver: "佐伯イッテツ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 30,
    title: "束縛ボイス",
    liver: "佐伯イッテツ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 31,
    title: "家族パロディボイス",
    liver: "シェリン・バーガンディ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 32,
    title: "ジューンブライドボイス2023",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 33,
    title: "束縛ボイス",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 34,
    title: "Shoothing Voice",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 35,
    title: "お迎えボイス",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 36,
    title: "ほろ酔いボイス",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 37,
    title: "ほろ酔いボイスvol.2",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 38,
    title: "使用人ボイス",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 39,
    title: "家族パロディボイスvol.2",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 40,
    title: "看病ボイス",
    liver: "小柳ロウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 41,
    title: "甘やかしボイスvol.2",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 42,
    title: "束縛ボイスvol.2",
    liver: "緋八マナ",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 43,
    title: "がんばらないボイス",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 44,
    title: "バレンタインボイス2024",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 45,
    title: "ホワイトデーボイス2024",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 46,
    title: "家族パロディボイス",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 47,
    title: "タイムスリップボイス",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 48,
    title: "トラベルボイス",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 49,
    title: "Shoothing Voice",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 50,
    title: "お迎えボイス",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 51,
    title: "家族パロディボイスvol.2（EN、JP）",
    liver: "ベンタクロウ･ブリンガー",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 52,
    title: "束縛ボイスvol.2",
    liver: "ミラン・ケストレル",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 53,
    title: "キミと夜空ボイス",
    liver: "叢雲カゲツ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 54,
    title: "ほろ酔いボイスvol.2",
    liver: "叢雲カゲツ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 55,
    title: "甘やかしボイスvol.2",
    liver: "叢雲カゲツ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 56,
    title: "束縛ボイス",
    liver: "叢雲カゲツ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 57,
    title: "束縛ボイスvol.2",
    liver: "叢雲カゲツ",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 58,
    title: "ジューンブライドボイス2024",
    liver: "叢雲カゲツ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 59,
    title: "わがままボイス",
    liver: "叢雲カゲツ",
    type: "セリフボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 60,
    title: "ツンデレボイス",
    liver: "叢雲カゲツ",
    type: "セリフボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 61,
    title: "内緒話ボイス",
    liver: "レオス・ヴィンセント",
    type: "セリフボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 62,
    title: "内緒話ボイス",
    liver: "渡会雲雀",
    type: "セリフボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
   {
    id: 63,
    title: "怪奇ボイス",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
   {
    id: 64,
    title: "兄弟・姉妹ボイス",
    liver: "伊波ライ",
    type: "セリフボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 65,
    title: "怪奇ボイス",
    liver: "緋八マナ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 66,
    title: "怪奇ボイス",
    liver: "星導ショウ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  }
];
