const voiceData = [
  {
    id: 1,
    title: "束縛ボイス",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♡♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: "https://"
  },
  {
    id: 2,
    title: "束縛ボイスvol.2",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 3,
    title: "ヒーローボイス",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 4,
    title: "ほろ酔いボイスvol.2",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 5,
    title: "家族パロディボイスvol.2",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 6,
    title: "がんばらないボイス",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 7,
    title: "わがままボイス",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 8,
    title: "ツンデレボイス",
    liver: "赤城ウェン",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 9,
    title: "ジューンブライドボイス2024",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 10,
    title: "ホワイトデーボイス2024",
    liver: "伊波ライ",
    type: "コンセプトボイス",
    status: "期間終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "purchased",
    review: "〇〇",
    url: ""
  }
];
