// 【exStatus の指定パターン】
// ex_purchased : 「EXあり（購入済）」のみ
// ex_p_exa_u   : 「EXあり（購入済）」＋「EXAあり（未購入）」
// ex_u_exa_p   : 「EXあり（未購入）」＋「EXAあり（購入済）」
// ex_p_exa_p   : 「EXあり（購入済）」＋「EXAあり（購入済）」
// ex_u_exa_u   : 「EXあり（未購入）」＋「EXAあり（未購入）」
// none         : 「EXなし」
// 【type の指定パターン】
// ★「コンセプトボイス」「セリフボイス」「ルート選択ボイス」のいずれか

const voiceData = [
  {
    id: 1,
    title: "束縛ボイス",
    liver: "赤城ウェン",
    titleKana: "そくばくぼいす",
    liverKana: "あかぎうぇん",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♡♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-00062_A.html"
  },
  {
    id: 2,
    title: "束縛ボイスvol.2",
    liver: "赤城ウェン",
    titleKana: "そくばくぼいすぼりゅーむつー",
    liverKana: "あかぎうぇん",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "https://shop.nijisanji.jp/dig-00096_A.html",
    url: ""
  },
  {
    id: 3,
    title: "ヒーローボイス",
    liver: "赤城ウェン",
    titleKana: "ひーろーぼいす",
    liverKana: "あかぎうぇん",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♡♡",
    tags: ["嫉妬", "かわいい", "恋人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-01489.html"
  },
  {
    id: 4,
    title: "ほろ酔いボイスvol.2",
    liver: "赤城ウェン",
    titleKana: "ほろよいぼいすぼりゅーむつー",
    liverKana: "あかぎうぇん",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♡♡♡",
    tags: ["嫉妬", "かわいい", "先輩・後輩"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-01456.html"
  },
  {
    id: 5,
    title: "家族パロディボイスvol.2",
    liver: "赤城ウェン",
    titleKana: "かぞくぱろでぃぼいすぼりゅーむつー",
    liverKana: "あかぎうぇん",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♡♡♡♡",
    tags: ["嫉妬", "かわいい", "兄弟・姉妹"],
    exStatus: "none",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-00050_A.html"
  },
  {
    id: 6,
    title: "がんばらないボイス",
    liver: "赤城ウェン",
    titleKana: "がんばらないぼいす",
    liverKana: "あかぎうぇん",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 7,
    title: "わがままボイス",
    liver: "赤城ウェン",
    titleKana: "わがままぼいす",
    liverKana: "あかぎうぇん",
    type: "セリフボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "恋人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 8,
    title: "ツンデレボイス",
    liver: "赤城ウェン",
    titleKana: "つんでれぼいす",
    liverKana: "あかぎうぇん",
    type: "セリフボイス",
    status: "販売終了",
    sweetness: "♥♥♥♡♡",
    tags: ["嫉妬", "かわいい", "恋人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 9,
    title: "ジューンブライドボイス2024",
    liver: "伊波ライ",
    titleKana: "じゅーんぶらいどぼいすにせんにじゅうよん",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-00043_A.html"
  },
  {
    id: 10,
    title: "ホワイトデーボイス2024",
    liver: "伊波ライ",
    titleKana: "ほわいとでーぼいすにせんにじゅうよん",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-01526.html"
  },
  {
    id: 11,
    title: "シェアハウスボイス",
    liver: "伊波ライ",
    titleKana: "しぇあはうすぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 12,
    title: "お迎えボイス",
    liver: "伊波ライ",
    titleKana: "おむかえぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 13,
    title: "キミと夜空ボイス",
    liver: "伊波ライ",
    titleKana: "きみとよぞらぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 14,
    title: "夜更かしボイス",
    liver: "伊波ライ",
    titleKana: "よふかしぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 15,
    title: "パーティーボイス",
    liver: "伊波ライ",
    titleKana: "ぱーてぃーぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 16,
    title: "アイドルパロディボイス",
    liver: "伊波ライ",
    titleKana: "あいどるぱろでぃぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 17,
    title: "ほろ酔いボイス",
    liver: "伊波ライ",
    titleKana: "ほろよいぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-01456.html"
  },
  {
    id: 18,
    title: "ほろ酔いボイスvol.2",
    liver: "伊波ライ",
    titleKana: "ぱーてぃーぼいすぼりゅーむつー",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 19,
    title: "ミニライバーボイス",
    liver: "伊波ライ",
    titleKana: "みにらいばーぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 20,
    title: "Soothing Voice",
    liver: "伊波ライ",
    titleKana: "すーじんぐぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 21,
    title: "束縛ボイスvol.2",
    liver: "伊波ライ",
    titleKana: "そくばくぼいすぼりゅーむつー",
    liverKana: "いなみらい",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 22,
    title: "バレンタインボイス2024",
    liver: "伊波ライ",
    titleKana: "ばれんたいんぼいすにせんにじゅうよん",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 23,
    title: "わがままボイス",
    liver: "伊波ライ",
    titleKana: "わがままぼいす",
    liverKana: "いなみらい",
    type: "セリフボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 24,
    title: "ツンデレボイス",
    liver: "伊波ライ",
    titleKana: "つんでれぼいす",
    liverKana: "いなみらい",
    type: "セリフボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 25,
    title: "バレンタインボイス2024",
    liver: "宇佐美リト",
    titleKana: "ばれんたいんぼいすにせんにじゅうよん",
    liverKana: "うさみりと",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 26,
    title: "束縛ボイスvol.2",
    liver: "宇佐美リト",
    titleKana: "そくばくぼいすぼりゅーむつー",
    liverKana: "うさみりと",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 27,
    title: "バレンタインボイス2019",
    liver: "卯月コウ",
    titleKana: "ばれんたいんぼいすにせんにじゅうきゅう",
    liverKana: "うづきこう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 28,
    title: "ホワイトデーボイス2019",
    liver: "卯月コウ",
    titleKana: "ほわいとでーぼいすにせんにじゅうきゅう",
    liverKana: "うづきこう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 29,
    title: "ヴィランボイス",
    liver: "佐伯イッテツ",
    titleKana: "ヴぃらんぼいす",
    liverKana: "さいきいってつ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "怖い", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 30,
    title: "束縛ボイス",
    liver: "佐伯イッテツ",
    titleKana: "そくばくぼいす",
    liverKana: "さいきいってつ",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "怖い", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 31,
    title: "家族パロディボイス",
    liver: "シェリン・バーガンディ",
    titleKana: "かぞくぱろでぃぼいす",
    liverKana: "しぇりんばーがんでぃ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 32,
    title: "ジューンブライドボイス2023",
    liver: "小柳ロウ",
    titleKana: "じゅーんぶらいどぼいすにせんにじゅうさん",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 33,
    title: "束縛ボイス",
    liver: "小柳ロウ",
    titleKana: "そくばくぼいす",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 34,
    title: "Soothing Voice",
    liver: "小柳ロウ",
    titleKana: "すーじんぐぼいす",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 35,
    title: "お迎えボイス",
    liver: "小柳ロウ",
    titleKana: "おむかえぼいす",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 36,
    title: "ほろ酔いボイス",
    liver: "小柳ロウ",
    titleKana: "ほろよいぼいす",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: "https://shop.nijisanji.jp/dig-01456.html"
  },
  {
    id: 37,
    title: "ほろ酔いボイスvol.2",
    liver: "小柳ロウ",
    titleKana: "ほろよいぼいすぼりゅーむつー",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 38,
    title: "使用人ボイス",
    liver: "小柳ロウ",
    titleKana: "しようにんぼいす",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 39,
    title: "家族パロディボイスvol.2",
    liver: "小柳ロウ",
    titleKana: "かぞくぱろでぃぼいすぼりゅーむつー",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 40,
    title: "看病ボイス",
    liver: "小柳ロウ",
    titleKana: "かんびょうぼいす",
    liverKana: "こやなぎろう",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 41,
    title: "甘やかしボイスvol.2",
    liver: "緋八マナ",
    titleKana: "あまやかしぼいすぼりゅーむつー",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 42,
    title: "束縛ボイスvol.2",
    liver: "緋八マナ",
    titleKana: "そくばくぼいすぼりゅーむつー",
    liverKana: "ひばちまな",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 43,
    title: "がんばらないボイス",
    liver: "緋八マナ",
    titleKana: "がんばらないぼいす",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 44,
    title: "バレンタインボイス2024",
    liver: "緋八マナ",
    titleKana: "ばれんたいんぼいすにせんにじゅうよん",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 45,
    title: "ホワイトデーボイス2024",
    liver: "緋八マナ",
    titleKana: "ほわいとでーにせんにじゅうよん",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 46,
    title: "家族パロディボイス",
    liver: "緋八マナ",
    titleKana: "かぞくぱろでぃぼいす",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 47,
    title: "タイムスリップボイス",
    liver: "緋八マナ",
    titleKana: "たいむすりっぷぼいす",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 48,
    title: "トラベルボイス",
    liver: "緋八マナ",
    titleKana: "とらべるぼいす",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 49,
    title: "Shoothing Voice",
    liver: "緋八マナ",
    titleKana: "すーじんぐぼいす",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♡♡",
    tags: ["嫉妬", "かわいい", "恋人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 50,
    title: "お迎えボイス",
    liver: "緋八マナ",
    titleKana: "おむかえぼいす",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♡♡♡",
    tags: ["嫉妬", "かわいい", "恋人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 51,
    title: "家族パロディボイスvol.2（EN、JP）",
    liver: "ベンタクロウ･ブリンガー",
    titleKana: "かぞくぱろでぃぼいすぼりゅーむつー",
    liverKana: "べんたくろうぶりんがー",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 52,
    title: "束縛ボイスvol.2",
    liver: "ミラン・ケストレル",
    titleKana: "そくばくぼいすぼりゅーむつー",
    liverKana: "みらんけすとれる",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 53,
    title: "キミと夜空ボイス",
    liver: "叢雲カゲツ",
    titleKana: "きみとよぞらぼいす",
    liverKana: "むらくもかげつ",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 54,
    title: "ほろ酔いボイスvol.2",
    liver: "叢雲カゲツ",
    titleKana: "ほろよいぼいすぼりゅーむつー",
    liverKana: "むらくもかげつ",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 55,
    title: "甘やかしボイスvol.2",
    liver: "叢雲カゲツ",
    titleKana: "あまやかしぼいすぼりゅーむつー",
    liverKana: "むらくもかげつ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 56,
    title: "束縛ボイス",
    liver: "叢雲カゲツ",
    titleKana: "そくばくぼいす",
    liverKana: "むらくもかげつ",
    type: "コンセプトボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 57,
    title: "束縛ボイスvol.2",
    liver: "叢雲カゲツ",
    titleKana: "そくばくぼいすぼりゅーむつー",
    liverKana: "むらくもかげつ",
    type: "ルート選択ボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_p_exa_p",
    review: "〇〇",
    url: ""
  },
  {
    id: 58,
    title: "ジューンブライドボイス2024",
    liver: "叢雲カゲツ",
    titleKana: "じゅーんぶらいどぼいすにせんにじゅうよん",
    liverKana: "むらくもかげつ",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 59,
    title: "わがままボイス",
    liver: "叢雲カゲツ",
    titleKana: "わがままぼいす",
    liverKana: "むらくもかげつ",
    type: "セリフボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 60,
    title: "ツンデレボイス",
    liver: "叢雲カゲツ",
    titleKana: "つんでれぼいす",
    liverKana: "むらくもかげつ",
    type: "セリフボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 61,
    title: "内緒話ボイス",
    liver: "レオス・ヴィンセント",
    titleKana: "ないしょばなしぼいす",
    liverKana: "れおすヴぃんせんと",
    type: "セリフボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 62,
    title: "内緒話ボイス",
    liver: "渡会雲雀",
    titleKana: "ないしょばなしぼいす",
    liverKana: "わたらいひばり",
    type: "セリフボイス",
    status: "販売終了",
    sweetness: "♥♥♥♥♡",
    tags: ["嫉妬", "かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
   {
    id: 63,
    title: "怪奇ボイス",
    liver: "伊波ライ",
    titleKana: "かいきぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♥♡♡♡",
    tags: ["ホラー", "かわいい", "恋人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
   {
    id: 64,
    title: "兄弟・姉妹ボイス",
    liver: "伊波ライ",
     titleKana: "きょうだいしまいぼいす",
    liverKana: "いなみらい",
    type: "セリフボイス",
    status: "販売中",
    sweetness: "♥♡♡♡♡",
    tags: ["嫉妬", "かわいい", "兄弟"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  },
  {
    id: 65,
    title: "怪奇ボイス",
    liver: "緋八マナ",
    titleKana: "かいきぼいす",
    liverKana: "ひばちまな",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♡♡♡♡",
    tags: ["ホラー", "かわいい", "恋人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 66,
    title: "怪奇ボイス",
    liver: "星導ショウ",
    titleKana: "かいきぼいす",
    liverKana: "ほしるべしょう",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♡♡♡♡♡",
    tags: ["ホラー", "怖い", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
  {
    id: 66,
    title: "片思いボイス",
    liver: "赤城ウェン",
    titleKana: "かたおもいぼいす",
    liverKana: "あかぎうぇん",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♡♡♡♡",
    tags: ["かわいい", "友人"],
    exStatus: "ex_purchased",
    review: "〇〇",
    url: ""
  },
    {
    id: 66,
    title: "片思いボイス",
    liver: "伊波ライ",
    titleKana: "かたおもいぼいす",
    liverKana: "いなみらい",
    type: "コンセプトボイス",
    status: "販売中",
    sweetness: "♥♡♡♡♡",
    tags: ["かわいい", "友人"],
    exStatus: "none",
    review: "〇〇",
    url: ""
  }
];
